# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Disable shared folder for all VMs
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Base box - different for different providers
  config.vm.box = "generic/ubuntu2204"

  # Disable automatic box update checking
  config.vm.box_check_update = false

  # Configure VirtualBox provider
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end

  # Master node for Kubernetes
  config.vm.define "master" do |master|
    master.vm.hostname = "master-node"
    
    # VirtualBox configuration
    master.vm.network "private_network", ip: "192.168.56.10"
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 2
    end
    
    # Docker provider configuration
    master.vm.provider "docker" do |d|
      # Don't use 'box' for Docker, use 'image' instead
      d.image = "ubuntu:22.04"
      d.name = "master-node"
      d.has_ssh = true
      d.privileged = true
      d.ports = ["2210:22", "6443:6443"]
      d.create_args = ["--hostname=master-node"]
      d.remains_running = true
    end
  end

  # Worker nodes
  (1..2).each do |i|
    config.vm.define "worker#{i}" do |worker|
      worker.vm.hostname = "worker-node-#{i}"
      
      # VirtualBox configuration
      worker.vm.network "private_network", ip: "192.168.56.#{10 + i}"
      worker.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = 2
      end
      
      # Docker provider configuration
      worker.vm.provider "docker" do |d|
        ssh_port = 2210 + i
        d.image = "ubuntu:22.04"
        d.name = "worker-node-#{i}"
        d.has_ssh = true
        d.privileged = true
        d.ports = ["#{ssh_port}:22"]
        d.create_args = ["--hostname=worker-node-#{i}"]
        d.remains_running = true
      end
    end
  end

  # Jenkins/CI node
  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.hostname = "jenkins-server"
    
    # VirtualBox configuration
    jenkins.vm.network "private_network", ip: "192.168.56.20"
    jenkins.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 2
    end
    
    # Docker provider configuration
    jenkins.vm.provider "docker" do |d|
      d.image = "jenkins/jenkins:lts-jdk17"
      d.name = "jenkins-server"
      d.has_ssh = false  # Jenkins image doesn't have SSH by default
      d.ports = ["8080:8080", "50000:50000"]
      d.create_args = ["--hostname=jenkins-server"]
      d.volumes = ["jenkins_data:/var/jenkins_home"]
      d.env = { "JENKINS_OPTS" => "--prefix=/" }
      d.remains_running = true
    end
  end

  # Monitoring node
  config.vm.define "monitoring" do |monitoring|
    monitoring.vm.hostname = "monitoring-server"
    
    # VirtualBox configuration
    monitoring.vm.network "private_network", ip: "192.168.56.30"
    monitoring.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 2
    end
    
    # Docker provider configuration
    monitoring.vm.provider "docker" do |d|
      d.image = "ubuntu:22.04"
      d.name = "monitoring-server"
      d.has_ssh = true
      d.ports = ["2230:22", "3000:3000", "9090:9090"]
      d.create_args = ["--hostname=monitoring-server"]
      d.remains_running = true
    end
  end
end
